// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netrin.EFCore.WebApi;

#nullable disable

namespace Netrin.EFCore.WebApi.Repository.Migrations
{
    [DbContext(typeof(PessoaContext))]
    [Migration("20241003224003_001")]
    partial class _001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Netrin.EFCore.WebApi.Domain.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dat_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("lon_telefone")
                        .HasColumnType("bigint");

                    b.Property<string>("str_cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("str_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("str_nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Netrin.EFCore.WebApi.Domain.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("dat_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("lon_telefone")
                        .HasColumnType("bigint");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("str_cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("str_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("str_nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Netrin.EFCore.WebApi.Domain.Endereco", b =>
                {
                    b.HasOne("Netrin.EFCore.WebApi.Domain.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
